// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MvcTraining.Models;

#nullable disable

namespace MvcTraining.Migrations
{
    [DbContext(typeof(MvcDbStokContext))]
    [Migration("20240415191203_tables")]
    partial class tables
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MvcTraining.Models.Tblkategoriler", b =>
                {
                    b.Property<short>("Kategoriid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasColumnName("KATEGORIID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<short>("Kategoriid"));

                    b.Property<string>("Kategoriad")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("KATEGORIAD");

                    b.HasKey("Kategoriid")
                        .HasName("PK_TBLKATEGORIAD");

                    b.ToTable("TBLKATEGORILER", (string)null);
                });

            modelBuilder.Entity("MvcTraining.Models.Tblmusteriler", b =>
                {
                    b.Property<int>("Musteriid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MUSTERIID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Musteriid"));

                    b.Property<string>("Musteriad")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("MUSTERIAD");

                    b.Property<string>("Musterisoyad")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("MUSTERISOYAD");

                    b.HasKey("Musteriid");

                    b.ToTable("TBLMUSTERILER", (string)null);
                });

            modelBuilder.Entity("MvcTraining.Models.Tblsatislar", b =>
                {
                    b.Property<int>("Satisid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("SATISID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Satisid"));

                    b.Property<byte?>("Adet")
                        .HasColumnType("tinyint")
                        .HasColumnName("ADET");

                    b.Property<decimal?>("Fiyat")
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("FIYAT");

                    b.Property<int?>("Musteri")
                        .HasColumnType("int")
                        .HasColumnName("MUSTERI");

                    b.Property<int?>("Urun")
                        .HasColumnType("int")
                        .HasColumnName("URUN");

                    b.HasKey("Satisid");

                    b.HasIndex("Musteri");

                    b.HasIndex("Urun");

                    b.ToTable("TBLSATISLAR", (string)null);
                });

            modelBuilder.Entity("MvcTraining.Models.Tblurunler", b =>
                {
                    b.Property<int>("Urunid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("URUNID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Urunid"));

                    b.Property<decimal?>("Fiyat")
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("FIYAT");

                    b.Property<string>("Marka")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("MARKA");

                    b.Property<byte?>("Stok")
                        .HasColumnType("tinyint")
                        .HasColumnName("STOK");

                    b.Property<string>("Urunad")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("URUNAD");

                    b.Property<short?>("Urunkategori")
                        .HasColumnType("smallint")
                        .HasColumnName("URUNKATEGORI");

                    b.HasKey("Urunid");

                    b.HasIndex("Urunkategori");

                    b.ToTable("TBLURUNLER", (string)null);
                });

            modelBuilder.Entity("MvcTraining.Models.Tblsatislar", b =>
                {
                    b.HasOne("MvcTraining.Models.Tblmusteriler", "MusteriNavigation")
                        .WithMany("Tblsatislars")
                        .HasForeignKey("Musteri")
                        .HasConstraintName("FK_TBLSATISLAR_TBLMUSTERILER");

                    b.HasOne("MvcTraining.Models.Tblurunler", "UrunNavigation")
                        .WithMany("Tblsatislars")
                        .HasForeignKey("Urun")
                        .HasConstraintName("FK_TBLSATISLAR_TBLURUNLER");

                    b.Navigation("MusteriNavigation");

                    b.Navigation("UrunNavigation");
                });

            modelBuilder.Entity("MvcTraining.Models.Tblurunler", b =>
                {
                    b.HasOne("MvcTraining.Models.Tblkategoriler", "UrunkategoriNavigation")
                        .WithMany("Tblurunlers")
                        .HasForeignKey("Urunkategori")
                        .HasConstraintName("FK_TBLURUNLER_TBLKATEGORILER");

                    b.Navigation("UrunkategoriNavigation");
                });

            modelBuilder.Entity("MvcTraining.Models.Tblkategoriler", b =>
                {
                    b.Navigation("Tblurunlers");
                });

            modelBuilder.Entity("MvcTraining.Models.Tblmusteriler", b =>
                {
                    b.Navigation("Tblsatislars");
                });

            modelBuilder.Entity("MvcTraining.Models.Tblurunler", b =>
                {
                    b.Navigation("Tblsatislars");
                });
#pragma warning restore 612, 618
        }
    }
}
